#Basics of Numpy **Arrays**

Numpy is a package for scientific computing which has support for a powerful n-dimensional array object.

In [1]:
#importing the main library.
import numpy as np

In [2]:
#creating an array of Integers.
arr_int = np.array([1,2,3], dtype = "int")
print(arr_int)
print("Type of numpy array : ", type(arr_int))
print("Data type of the numpy array : ", arr_int.dtype)
print("Dimension of the numpy array : ", arr_int.shape)

[1 2 3]
Type of numpy array :  <class 'numpy.ndarray'>
Data type of the numpy array :  int64
Dimension of the numpy array :  (3,)


In [3]:
#creating an array of type float
arr_float = np.array([1,2,3], dtype = "float")
print(arr_float)
print("Type of the numpy array : ", type(arr_float))
print("Data type of the numpy array : ", arr_float.dtype)
print("Dimensions of the numpy array : ", arr_float.shape)

[1. 2. 3.]
Type of the numpy array :  <class 'numpy.ndarray'>
Data type of the numpy array :  float64
Dimensions of the numpy array :  (3,)


In [4]:
#creating an array of complex numbers
arr_complex = np.array([1,2j,3 + 3j], dtype = "complex")
print(arr_complex)
print("Type of the numpy array : ", type(arr_complex))
print("Data type of the numpy array : ", arr_complex.dtype)
print("Dimensions of the numpy array : ", arr_complex.shape)

print("=========================================")
print("Real part : ", np.real(arr_complex))
print("Imaginary part : ", np.imag(arr_complex))
print("Conjugate : ", np.conj(arr_complex))
print("Angle in radian : ", np.angle(arr_complex))
print("Angle in degrees : ", np.angle(arr_complex, deg=True))

[1.+0.j 0.+2.j 3.+3.j]
Type of the numpy array :  <class 'numpy.ndarray'>
Data type of the numpy array :  complex128
Dimensions of the numpy array :  (3,)
Real part :  [1. 0. 3.]
Imaginary part :  [0. 2. 3.]
Conjugate :  [1.-0.j 0.-2.j 3.-3.j]
Angle in radian :  [0.         1.57079633 0.78539816]
Angle in degrees :  [ 0. 90. 45.]


Matrix Operations using Numpy

Multiplication using numpy arrays also known as vectorization has the main aim to reduce or remove the explicit use of for loops in the program making the computation speed up.
Numpy is a build in a package in python for array-processing and manipulation.For larger matrix operations we use numpy python package which is 1000 times faster than iterative one method.

In [5]:
mat1 = np.array([[1, 2, 3], [1, 0, 1]])
mat2 = np.array([[1, 2, 1], [1, 1, 1]])

print("Shape of matrix 1 : ", mat1.shape)
print("No. of rows : {} \nNo. of columns : {}".format(mat1.shape[0], mat1.shape[1]))
print("Shape of matrix 2 : ", mat2.shape)
print("No. of rows : {} \nNo. of columns : {}".format(mat2.shape[0], mat2.shape[1]))

Shape of matrix 1 :  (2, 3)
No. of rows : 2 
No. of columns : 3
Shape of matrix 2 :  (2, 3)
No. of rows : 2 
No. of columns : 3


In [6]:
#Arithmetic Operations

print("Mat 1 : \n", mat1)
print("Mat 2 : \n", mat2)

#1) Addition
print(np.add(mat1, mat2))

#2) Subtraction
print(np.subtract(mat1, mat2))

#3) Multiplication [performs element wise product]
print(np.multiply(mat1, mat2))

#4) Division
print(np.divide(mat1, mat2))


Mat 1 : 
 [[1 2 3]
 [1 0 1]]
Mat 2 : 
 [[1 2 1]
 [1 1 1]]
[[2 4 4]
 [2 1 2]]
[[ 0  0  2]
 [ 0 -1  0]]
[[1 4 3]
 [1 0 1]]
[[1. 1. 3.]
 [1. 0. 1.]]


In [7]:
#creating a array filled with random values
mat3 = np.random.rand(3, 2)
mat3

array([[0.67698407, 0.37775915],
       [0.89106466, 0.73787107],
       [0.84334236, 0.13715661]])

In [8]:
#dot product
print("Mat 1 : ", mat1.shape)
print("Mat 3 : ", mat3.shape)

mat_dot = np.dot(mat1, mat3)
print(mat_dot)
print("Mat dot : ", mat_dot.shape)

Mat 1 :  (2, 3)
Mat 3 :  (3, 2)
[[4.98914047 2.26497111]
 [1.52032643 0.51491576]]
Mat dot :  (2, 2)


In [9]:
#Matrix Operations
print("Mat 1 : \n", mat1)
print("Mat 1 : ", mat1.shape)
print("Mat 3 : \n", mat3)
print("Mat 3 : ", mat3.shape)

#Transpose
print("Transpose of Mat 1 : ", mat1.T)
print("Mat transpose : ", mat1.T.shape)

#creating arrays of zeros
print("Array of zeros : \n", np.zeros((4,4)))

#creating arrays of ones
print("Arrays of ones : \n", np.ones((2, 6)))

#creating a continuous ranged array
print("Array : ", np.arange(6))
print("shape : ", np.arange(6).shape)
print("Reshaped : ", np.arange(6).reshape(2, -1))

Mat 1 : 
 [[1 2 3]
 [1 0 1]]
Mat 1 :  (2, 3)
Mat 3 : 
 [[0.67698407 0.37775915]
 [0.89106466 0.73787107]
 [0.84334236 0.13715661]]
Mat 3 :  (3, 2)
Transpose of Mat 1 :  [[1 1]
 [2 0]
 [3 1]]
Mat transpose :  (3, 2)
Array of zeros : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Arrays of ones : 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Array :  [0 1 2 3 4 5]
shape :  (6,)
Reshaped :  [[0 1 2]
 [3 4 5]]


In [10]:
#Accessing the matrix elements

mat = np.array([1,2,3,4,5,6,7,8])
print("Shape", mat.shape)
mat_r = mat.reshape(-1, 1)
print(mat_r)
print(mat_r.shape)

Shape (8,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(8, 1)


In [11]:
#1D matrix
print("First element : ", mat[0])
print("Last element : ", mat[-1])

First element :  1
Last element :  8


In [12]:
#2D matrix
mat1[-1][-1] = 10 
print("2D matrix : \n", mat1)
print("shape", mat1.shape)

print("First element of first row : ", mat1[0][0])
print("Last element of last row : ", mat1[-1][-1])
print("First row : ", mat1[0])
print("Last row : ", mat1[-1])
print("First column : ", mat1[:, 0])
print("Last column : ", mat1[:, -1])

2D matrix : 
 [[ 1  2  3]
 [ 1  0 10]]
shape (2, 3)
First element of first row :  1
Last element of last row :  10
First row :  [1 2 3]
Last row :  [ 1  0 10]
First column :  [1 1]
Last column :  [ 3 10]


In [13]:
#Slicing of matrix
print("mat : ", mat)

print(mat[:]) #entire matrix
print(mat[:5])
print(mat[1:4])
print(mat[:-1]) #all except last one.
print(mat[:-5])

print("========================================")
print("mat1 : \n", mat1)
print(mat1[:-1]) #all rows except last one
print()
print(mat1[:, 1:3])

mat :  [1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5]
[2 3 4]
[1 2 3 4 5 6 7]
[1 2 3]
mat1 : 
 [[ 1  2  3]
 [ 1  0 10]]
[[1 2 3]]

[[ 2  3]
 [ 0 10]]


In [14]:
#reversing the array
print("Original array : ", arr_int)
print("Reversed array : ", arr_int[::-1])

Original array :  [1 2 3]
Reversed array :  [3 2 1]


In [20]:
#creating an array using repeating list
rep = np.array([1,2,3] * 3)
print(rep)
print(rep.reshape(3, -1))

[1 2 3 1 2 3 1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


#Usage of Numpy in ML/AI

In [25]:
#mathematical functions
a = np.array([1, 2, 3, 4, 0])
print(a.sum())
print(a.max())
print(a.min())
print(a.mean())
print(a.std())

print(a.argmax()) #index of the max element.
print(a.argmin())

10
4
0
2.0
1.4142135623730951
3
4


In [17]:
#creating an evenly spaced numbers over a specified interval.
spaced = np.linspace(0, 10, 5) #0 to 10 in 5 equal partitions
spaced

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
#typecasting to a specific type
a = np.array([[1,2],[3,4]])
print(a.dtype)
a = a.astype('f')
print(a.dtype)

int64
float32


#Saving and loading numpy arrays

In [40]:
#importing the necessary modules
from numpy import asarray
from numpy import savetxt, loadtxt, save, load

In [34]:
#saving a numpy array to csv file
arr1 = np.array([[1,2,3,4], [5,6,7,8]], dtype="int")
print(arr.shape)
savetxt('arr1.csv', arr1, delimiter=',')
print(arr1)

(1, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [35]:
#loading the saved csv file
import os
os.listdir()
data_csv = loadtxt('arr1.csv', delimiter=',')
data_csv

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [37]:
#saving a numpy array to npy file
save('arr1.npy', arr1)

In [41]:
#loading the array from npy file
data_npy = load('arr1.npy')
data_npy

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])